INSERT INTO tb_EventType
VALUES
('Futebol de Campo'),
('Futebol de Salão'),
('Tênis'),
('Corrida'),
('Vôlei'),
('Basquete'),
('Ciclismo'),
('Handball'),
('Beach Tênis'),
('Caminhada'),
('Crossfit'),
('Dança'),
('Futebol Americano'),
('Futevôlei'),
('Meditação'),
('Patins'),
('Rugby'),
('Skate'),
('Slackline'),
('Stand up'),
('Surf'),
('Trilha'),
('Yoga')